name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Faster since testing against production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest webdriver-manager python-dotenv requests

    - name: Clean up any existing Chrome processes
      run: |
        sudo pkill -f chrome || true
        sudo pkill -f chromedriver || true

    - name: Run tests against production
      env:
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: |
        pytest tests/test_login.py

    - name: Clean up Chrome processes after tests
      if: always()
      run: |
        sudo pkill -f chrome || true
        sudo pkill -f chromedriver || true
